### ISSUE TITLE
Alternative for jstat command

### ISSUE THREAD

**Issue by anouarchattouna** [apangin/jattach#36]
Hello,

What is the closest alternative for `jstat` command (example: `jstat -gc <vmid> <interval>`) ?

Best,

**Comment by apangin** [comment]
`jstat` is based on completely different mechanism.

`jstat` reads [Jvmstat Performance Counters](http://openjdk.java.net/groups/hotspot/docs/Serviceability.html#bjvmstat) from hsperfdata file, while `jattach` relies on Dynamic Attach Mechanism. See [this answer](https://stackoverflow.com/a/55670479/3448419) for details.

It's possible to start local Management Agent with jattach (`jcmd ManagementAgent.start_local`), so that GC and other counters will be available through JMX. Otherwise there is no relation between `jstat` and `jattach`.

**Comment by anouarchattouna** [comment]
Thank you.
