### ISSUE TITLE
I think someone else is using your code

### ISSUE THREAD

**Issue by TaylorSasser** [apangin/jattach#9]
I found this code online and it is very similar to your copyrighted code.

http://cr.openjdk.java.net/~dcubed/7028668-webrev/0/src/windows/native/sun/tools/attach/WindowsVirtualMachine.c.html

**Comment by ui4j** [comment]
Could you please show us similarities

**Comment by TaylorSasser** [comment]
Updated it to right link

**Comment by apangin** [comment]
The above fragment actually comes from JDK sources. This is a native part of Java Attach API.

`jattach` is a re-implementation of Dynamic Attach API in pure C. Though it is a clean-room implementation, of course, it is similar to what JDK does because of non-standard `JVM_EnqueueOperation` mechanism which is the key entry point for attaching to HotSpot on Windows. Not sure if this requires further actions.
